
browser= chrome
AppURL=https://yellow-dune-0dc4f8f1e.5.azurestaticapps.net/sign-in
DFUserName=thisiskrishnagajula@gmail.com
Password=Test@123
patientuser=krishnagajula@gmail.com
doctorFacilityUser=thisiskrishnagajula@gmail.com
doctorFacility1=MedicalFacilityAutoTest
RequestType=Civil Subpoena
PAGE_LOAD_TIME_OUT=20
IMPLICIT_WAIT=10